name: "Azure Docker Build and Push"
author: "Stefan Bess"
branding:
  icon: "code"
  color: "green"
description: "Build and push a Docker image to Azure Container Registry (ACR)"
inputs:
  service_principal:
    description: "Service Principal with Contributor role on the ACR"
    required: true
  service_principal_password:
    description: "Service Principal password"
    required: true
  tenant:
    description: "Azure Container Registry tenant"
    required: true
  registry:
    description: "The name of the ACR, minus the .azurecr.io"
    required: true
  repository:
    description: "Repository to use (defaults to current repo)"
    required: false
  git_access_token:
    description: "Github access token for private repositories"
    required: true
  image:
    description: "Docker image name"
    required: false
  tag:
    description: "Docker image tag, default to the commit SHA"
    required: false
  branch:
    description: "Branch to build from, defaults to master"
    required: false
  folder:
    description: "The folder in the Github repo that holds the source"
    required: true
  dockerfile:
    description: "The location of the Dockerfile; defaults to ./Dockerfile"
    required: false
  build_args:
    description: "JSON specifying key=value pairs as as Docker build arguments"
    required: false
outputs:
  ci_repository_name:
    description: "The name of the repository without the owner prefix"
  ci_action_ref_name:
    description: "The branch or tag name that triggered the workflow"
  node_version:
    description: "Node.js version read from the .node-version file"
runs:
  using: "docker"
  image: "Dockerfile"